server:
  port: 2020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_shiro?useSSL=false&serverTimezone=UTC
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  # 模板配置
  thymeleaf:
    cache: false
    mode: HTML

  redis:
    host: 192.168.101.12
    port: 6379
    password: redisadmin
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    database: 0

  shiro:
    # 允许匿名访问的url地址
    ignoreAuthUrl:
      - /static/**
      - /test
      - /testDemo

